version: "3.3"
services:
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    networks:
      - app_network

  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8010:8001
    volumes:
      - redis_insight_volume_data:/db
    depends_on:
      - redis
    networks:
      - app_network

  fastapi_app:
    build:
      context: C:\NextCode\slices-task-schedular
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - app_network

volumes:
  redis_volume_data:
  redis_insight_volume_data:

networks:
  app_network:
    driver: bridge