version: "3.3"
services:
  fastapi_app:
    build:
      context: D:\NextCode\slices-task-schedular
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app_network

volumes:
  redis_volume_data:
  redis_insight_volume_data:

networks:
  app_network:
    driver: bridge