name: Deploy to ECR

on:
  push:
    branches:
      - uat  # Adjust to the branch you want to trigger on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Prune Docker resources to free space
        run: |
          docker system prune -af --volumes

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_UAT }}

      - name: Build and push Redis image
        run: |
          docker pull redis:6.0.7
          docker tag redis:6.0.7 ${{ secrets.ECR_REPOSITORY_UAT }}/redis:6.0.7
          docker push ${{ secrets.ECR_REPOSITORY_UAT }}/redis:6.0.7

      - name: Build and push RedisInsight image
        run: |
          docker pull redislabs/redisinsight:1.14.0
          docker tag redislabs/redisinsight:1.14.0 ${{ secrets.ECR_REPOSITORY_UAT }}/redisinsight:1.14.0
          docker push ${{ secrets.ECR_REPOSITORY_UAT }}/redisinsight:1.14.0

      - name: Build and push FastAPI app
        run: |
          docker build -t fastapi-app .
          docker tag fastapi-app:latest ${{ secrets.ECR_REPOSITORY_UAT }}/fastapi-app:latest
          docker push ${{ secrets.ECR_REPOSITORY_UAT }}/fastapi-app:latest